<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\TestWork.GraphApp.Core\TestWork.GraphApp.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="hostdbmgd">
			<HintPath>..\Libs\hostdbmgd.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="hostmgd">
			<HintPath>..\Libs\hostmgd.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="imapimgd">
			<HintPath>..\Libs\imapimgd.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="MapiBaseTypes">
			<HintPath>..\Libs\mapibasetypes.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="mapimgd">
			<HintPath>..\Libs\mapimgd.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="mapinet">
			<HintPath>..\Libs\mapinet.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>

</Project>
